### PR TITLE
added gitignore and code cleanup

### PR DESCRIPTION
**Pull request by Prajwal-P**
- Added gitignore file to ignore dataset folder and python cache files
- Fixed load dataset function
- Updated requirements file
- Added autopep8 formatter
- Will update readme file

### CODE REVIEW

**Comment by Prajwal-P** [comment]
# IMPORTANT!!!
@Rahulgupta9244 @PratikPailwan @Revanthpn
When this PR is merged delete your old conda environments, create a new one and then install packages from the new requirements files.

In addition to the above point, if you guys understand [this note] then reply to this comment so that I can remove this PR from draft state and continue with the review and merging.

Please so this asap so that we can continue with other issues.

[this note]: https://github.com/Prajwal-P/Safe-Distance-and-Face-Mask-Detection-using-Deep-Learning/tree/hotfix/clean-up#note

**Review by PratikPailwan — DISMISSED** [review]

**Review by Revanthpn — DISMISSED** [review]

**Comment by Revanthpn** [comment]
> # IMPORTANT!!!
> @Rahulgupta9244 @PratikPailwan @Revanthpn
> When this PR is merged delete your old conda environments, create a new one and then install packages from the new requirements files.
> 
> In addition to the above point, if you guys understand [this note](https://github.com/Prajwal-P/Safe-Distance-and-Face-Mask-Detection-using-Deep-Learning/tree/hotfix/clean-up#note) then reply to this comment so that I can remove this PR from draft state and continue with the review and merging.
> 
> Please do this asap so that we can continue with other issues.

Okay

**Comment by PratikPailwan** [comment]
> # IMPORTANT!!!
> @Rahulgupta9244 @PratikPailwan @Revanthpn
> When this PR is merged delete your old conda environments, create a new one and then install packages from the new requirements files.
> 
> In addition to the above point, if you guys understand [this note](https://github.com/Prajwal-P/Safe-Distance-and-Face-Mask-Detection-using-Deep-Learning/tree/hotfix/clean-up#note) then reply to this comment so that I can remove this PR from draft state and continue with the review and merging.
> 
> Please do this asap so that we can continue with other issues.

okay

**Comment by Rahulgupta9244** [comment]
> # IMPORTANT!!!
> @Rahulgupta9244 @PratikPailwan @Revanthpn
> When this PR is merged delete your old conda environments, create a new one and then install packages from the new requirements files.
> 
> In addition to the above point, if you guys understand [this note](https://github.com/Prajwal-P/Safe-Distance-and-Face-Mask-Detection-using-Deep-Learning/tree/hotfix/clean-up#note) then reply to this comment so that I can remove this PR from draft state and continue with the review and merging.
> 
> Please do this asap so that we can continue with other issues.

okay.. got you man.

**Review by Revanthpn — DISMISSED** [review]

**Review by Revanthpn — APPROVED** [review]

**Review by PratikPailwan — APPROVED** [review]

**Pull request merged**
